#    ███╗░░░███╗░█████╗░██████╗░  ██████╗░██╗░░░██╗███╗░░██╗░██████╗░███████╗░█████╗░███╗░░██╗░██████╗
#    ████╗░████║██╔══██╗██╔══██╗  ██╔══██╗██║░░░██║████╗░██║██╔════╝░██╔════╝██╔══██╗████╗░██║██╔════╝
#    ██╔████╔██║███████║██████╔╝  ██║░░██║██║░░░██║██╔██╗██║██║░░██╗░█████╗░░██║░░██║██╔██╗██║╚█████╗░
#    ██║╚██╔╝██║██╔══██║██╔═══╝░  ██║░░██║██║░░░██║██║╚████║██║░░╚██╗██╔══╝░░██║░░██║██║╚████║░╚═══██╗
#    ██║░╚═╝░██║██║░░██║██║░░░░░  ██████╔╝╚██████╔╝██║░╚███║╚██████╔╝███████╗╚█████╔╝██║░╚███║██████╔╝
#    ╚═╝░░░░░╚═╝╚═╝░░╚═╝╚═╝░░░░░  ╚═════╝░░╚═════╝░╚═╝░░╚══╝░╚═════╝░╚══════╝░╚════╝░╚═╝░░╚══╝╚═════╝░
# Config version: 1.0.0

# Can be either SQLite or MySQL
used-database: 'mysql'
mysql:
  address: 'localhost:3306'
  database: 'myDatabase'